export const mockCharacters = [
  {
    _id: '5cd99d4bde30eff6ebccfbbe',
    name: 'Adanel',
    wikiUrl: 'http://lotr.wikia.com//wiki/Adanel',
    race: 'Human',
    birth: null,
    gender: 'Female',
    death: null,
    hair: null,
    height: null,
    realm: null,
    spouse: 'Belemir',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbbf',
    name: 'Adrahil I',
    wikiUrl: 'http://lotr.wikia.com//wiki/Adrahil_I',
    race: 'Human',
    birth: 'Before ,TA 1944',
    gender: 'Male',
    death: 'Late ,Third Age',
    hair: null,
    height: null,
    realm: null,
    spouse: null,
  },
];
